batch_size: 2
workers: 16
nepoch: 100
model_name: dcp
load_model: null
#./log/dcp_mvp_debug_2022-09-05T01:47:55/network.pth
start_epoch: 0
work_dir: log/
flag: debug

manual_seed: null

step_interval_to_print: 200
step_interval_to_plot: 250
epoch_interval_to_save: 10
epoch_interval_to_val: 1


varying_constant_1: 0.001, 0.1, 1, 5
varying_constant_2: 5, 1, 0.1, 0.01
varying_constant_3: 0.01, 0.1, 1, 2
varying_constant_epochs: 15, 30, 50


lr: 0.001
lr_decay: True
lr_decay_rate: 0.5
lr_clip: 1.e-6
optimizer: Adam
weight_decay: 0
betas: 0.9, 0.999

use_rri: False
rri_size: 5
num_clusters: 16
num_points: 2048
use_tnet: False
use_fpfh: False
use_ppf: False
descriptor_size: 512
max_angle: 180
max_trans: 0.5
category: null
benchmark: mvp
num_rot_levels: 2
num_corr_levels: 2
