
batch_size: 4
workers: 16
nepoch: 200
model_name: idam
load_model: null
start_epoch: 0
work_dir: log/
flag: debug

manual_seed: null

varying_constant_1: 0.001, 0.1, 1, 5
varying_constant_2: 5, 1, 0.1, 0.01
varying_constant_3: 0.01, 0.1, 1, 2
varying_constant_epochs: 15, 30, 50

step_interval_to_print: 100
step_interval_to_plot: 250
epoch_interval_to_save: 1
epoch_interval_to_val: 1

lr: 0.0001
lr_decay: True
lr_decay_rate: 0.5
lr_clip: 1.e-4
optimizer: Adam
weight_decay: 0
betas: 0.9, 0.999

use_rri: False
rri_size: 20
num_groups: 16
num_points: 2048
# use_tnet: False
use_fpfh: False
use_ppf: False
descriptor_size: 64
num_iters: 3
layers: 1, 1, 1, 1
distribution_loss: KLD
knn_list: "16"
pk: 10
local_folding: True
points_label: True
num_coarse_raw: 10
num_fps: 2048
num_coarse: 2048

max_angle: 180
max_trans: 0.5
category: null
benchmark: mvp
num_rot_levels: 2
num_corr_levels: 2